package shit.zen.utils.misc;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public final class UiText {
    private static final Map<String, String> ZH_CN;

    static {
        Map<String, String> text = new HashMap<>();

        // Categories.
        text.put("Combat", "战斗");
        text.put("Movement", "移动");
        text.put("Player", "玩家");
        text.put("Render", "渲染");
        text.put("World", "世界");
        text.put("Misc", "杂项");
        text.put("Ghost", "辅助");

        // Modules and HUD elements.
        text.put("AimAssist", "辅助瞄准");
        text.put("AntiBots", "反机器人");
        text.put("AntiFireball", "反火球");
        text.put("AntiKB", "反击退");
        text.put("AntiStaff", "管理员检测");
        text.put("AntiTNT", "TNT 防护");
        text.put("AntiVoid", "虚空防护");
        text.put("AntiWeb", "蛛网脱困");
        text.put("AspectRatio", "宽高比");
        text.put("AutoClicker", "自动点击");
        text.put("AutoMLG", "自动落地保护");
        text.put("AutoOffHand", "自动副手");
        text.put("AutoPlay", "自动下一局");
        text.put("AutoRod", "自动钓竿");
        text.put("AutoSoup", "自动喝汤");
        text.put("AutoThrow", "自动投掷");
        text.put("AutoTools", "自动工具");
        text.put("AutoWebPlace", "自动放置蛛网");
        text.put("Backtrack", "回溯");
        text.put("ChestESP", "箱子透视");
        text.put("ChestStealer", "自动拿取箱子");
        text.put("ClickGui", "点击界面");
        text.put("CollisionSpeed", "碰撞加速");
        text.put("Compass", "指南针");
        text.put("Critical", "暴击");
        text.put("CrystalAura", "水晶光环");
        text.put("DamageGlow", "受伤高亮");
        text.put("Debugger", "调试器");
        text.put("Disabler", "禁用器");
        text.put("ESP", "实体标记");
        text.put("FastPlace", "快速放置");
        text.put("FastWeb", "快速脱网");
        text.put("FireballBlink", "火球延迟");
        text.put("Fly", "飞行");
        text.put("FullBright", "全亮");
        text.put("GhostHand", "隔墙交互");
        text.put("GuiMove", "界面移动");
        text.put("Helper", "辅助工具");
        text.put("HighJump", "高跳");
        text.put("Interface", "界面设置");
        text.put("InventoryManager", "背包管理");
        text.put("ItemTags", "物品标签");
        text.put("KeyBinds", "快捷键");
        text.put("KillAura", "杀戮光环");
        text.put("LieDetector", "测谎提示");
        text.put("MidPearl", "中键珍珠");
        text.put("ModuleList", "模块列表");
        text.put("NameProtect", "名称保护");
        text.put("NameTags", "名称标签");
        text.put("NoDelay", "无延迟");
        text.put("NoFall", "无摔落");
        text.put("NoHurtCam", "无受伤晃动");
        text.put("NoPush", "防推动");
        text.put("NoSlow", "无减速");
        text.put("OldHitting", "旧版攻击动画");
        text.put("PlayerList", "玩家列表");
        text.put("Effects", "药水效果");
        text.put("Projectiles", "投射物轨迹");
        text.put("SafeWalk", "安全行走");
        text.put("Scaffold", "自动搭路");
        text.put("Sprint", "自动疾跑");
        text.put("Stuck", "卡位");
        text.put("TargetHUD", "目标信息");
        text.put("TargetStrafe", "目标环绕");
        text.put("Teams", "队伍识别");
        text.put("Watermark", "水印");
        text.put("WebUI", "网页面板");
        text.put("XRay", "矿物透视");

        // Settings and mode values. Internal values remain English for config compatibility.
        text.put("ACA Aim Step", "ACA 瞄准步进");
        text.put("ACA Fast Switch", "ACA 快速切换");
        text.put("ACA Inventory Frequency", "ACA 背包频率");
        text.put("ACA Perfect Rotation", "ACA 完美旋转");
        text.put("Adaptive", "自适应");
        text.put("Adaptive Offset", "自适应偏移");
        text.put("Aim Range", "瞄准范围");
        text.put("Alpha", "透明度");
        text.put("Alternative Search Radius", "备用搜索半径");
        text.put("Ancient Debris", "远古残骸");
        text.put("Animals", "动物");
        text.put("Animation", "动画");
        text.put("Anti-Fake Ore", "反假矿");
        text.put("Arrows", "箭矢");
        text.put("Attack amount", "攻击次数");
        text.put("Attack Animals", "攻击动物");
        text.put("Attack Invisible", "攻击隐身目标");
        text.put("Attack Mobs", "攻击生物");
        text.put("Attack on Packet (Danger)", "收到数据包时攻击（危险）");
        text.put("Attack Player", "攻击玩家");
        text.put("Auto Armor", "自动穿甲");
        text.put("Auto Jump", "自动跳跃");
        text.put("Axe Slot", "斧槽位");
        text.put("Blind Render Range", "盲扫渲染范围");
        text.put("Blind Scan", "盲扫");
        text.put("Block Check", "方块检测");
        text.put("Block Lava", "封堵岩浆");
        text.put("Block Slot", "方块槽位");
        text.put("Block Type", "方块类型");
        text.put("Block Water", "封堵水源");
        text.put("Blocks", "方块");
        text.put("Both", "两侧");
        text.put("Bottom", "底部");
        text.put("Bow", "弓");
        text.put("Bow Priority", "弓优先级");
        text.put("Bow Slot", "弓槽位");
        text.put("Box", "方框");
        text.put("Break Block", "破坏方块");
        text.put("BrewingStand", "酿造台");
        text.put("Brightness", "亮度");
        text.put("Button", "按键");
        text.put("Chance", "概率");
        text.put("Check Sword", "检查剑");
        text.put("Chest", "箱子");
        text.put("Click Mode", "点击方式");
        text.put("Clutch", "自动救援");
        text.put("Coal", "煤矿");
        text.put("Color", "颜色");
        text.put("Color B", "蓝色分量");
        text.put("Color G", "绿色分量");
        text.put("Color R", "红色分量");
        text.put("Compass Only", "仅指南针");
        text.put("Copper", "铜矿");
        text.put("CPS Mode", "点击速度模式");
        text.put("CPS", "点击速度");
        text.put("Crossbow", "弩");
        text.put("Crystal Slot", "水晶槽位");
        text.put("Debug", "调试");
        text.put("Delay", "延迟");
        text.put("Delay Mode", "延迟模式");
        text.put("Diamond", "钻石矿");
        text.put("Distance", "距离");
        text.put("Drop", "丢弃");
        text.put("Drop Delay", "丢弃延迟");
        text.put("DynamicIsland", "灵动岛");
        text.put("Eagle", "边缘潜行");
        text.put("Eggs & Snowballs Slot", "鸡蛋与雪球槽位");
        text.put("Emerald", "绿宝石矿");
        text.put("Enable Alternative Start", "启用备用起点");
        text.put("Ender Chest", "末影箱");
        text.put("Ender Pearl Slot", "末影珍珠槽位");
        text.put("EndPortalFrame", "末地传送门框架");
        text.put("Extinguish Fire", "扑灭火焰");
        text.put("Fake AutoBlock", "模拟自动格挡");
        text.put("Fall Distance", "下落距离");
        text.put("Fall distance", "下落距离");
        text.put("Fast Throw", "快速投掷");
        text.put("Fishing Rod", "钓鱼竿");
        text.put("Fixed", "固定");
        text.put("Follow Direction", "跟随方向");
        text.put("Food", "食物");
        text.put("FoV", "视野角度");
        text.put("Fov", "视野角度");
        text.put("FOV", "视野角度");
        text.put("Furnace", "熔炉");
        text.put("Gapple", "金苹果");
        text.put("Glow", "发光");
        text.put("Gold", "金矿");
        text.put("Golden Apple", "金苹果");
        text.put("Golden Apple Slot", "金苹果槽位");
        text.put("Grim Fast", "Grim 快速");
        text.put("Grim Full", "Grim 完整");
        text.put("Grim Bad PacketsA", "Grim 异常数据包 A");
        text.put("Grim Duplicate RotPlace", "Grim 重复旋转放置");
        text.put("Ground Web", "地面蛛网");
        text.put("Health", "生命值");
        text.put("Health Bar Position", "生命条位置");
        text.put("Hide Teammates", "隐藏队友");
        text.put("Hurt Time", "受伤时间");
        text.put("Ignore skip ticks", "忽略跳过刻");
        text.put("Infinity Switch", "无限切换");
        text.put("Instant Attack", "立即攻击");
        text.put("Intercept", "拦截");
        text.put("Intercept Button", "拦截按键");
        text.put("Inventory Only", "仅背包界面");
        text.put("Invisibles", "隐身目标");
        text.put("Iron", "铁矿");
        text.put("Item Types", "物品类型");
        text.put("Items", "物品");
        text.put("Jump Key Only", "仅按跳跃键");
        text.put("Jump Reset", "跳跃重置");
        text.put("Keep Sprint", "保持疾跑");
        text.put("Keep Sprinting", "保持疾跑");
        text.put("Keep Y", "保持高度");
        text.put("Key", "按键");
        text.put("Lapis", "青金石矿");
        text.put("Lava", "岩浆");
        text.put("Lava Wait Water Bucket", "岩浆后等待水桶");
        text.put("Leaked", "泄露版");
        text.put("Left", "左侧");
        text.put("Legit", "拟真");
        text.put("Logging", "记录日志");
        text.put("Max APS", "最大每秒攻击数");
        text.put("Max Block Size", "最大方块数量");
        text.put("Max Distance", "最大距离");
        text.put("Max Eggs & Snowballs Size", "鸡蛋与雪球最大数量");
        text.put("Max Food Size", "最大食物数量");
        text.put("Max Range", "最大范围");
        text.put("Max Rod Size", "最大钓竿数量");
        text.put("MaxBlocks", "最大方块数");
        text.put("Method", "方法");
        text.put("Middle", "鼠标中键");
        text.put("Min Air Blocks Required", "最少空气方块数");
        text.put("Min APS", "最小每秒攻击数");
        text.put("Min Auth Score", "最低可信分数");
        text.put("Min Distance", "最小距离");
        text.put("Min Range", "最小范围");
        text.put("Minimum Vein Size", "最小矿脉大小");
        text.put("Mix", "混合");
        text.put("Mobs", "生物");
        text.put("Mode", "模式");
        text.put("More Particles", "更多粒子");
        text.put("Mouse", "鼠标");
        text.put("Mouse 4", "鼠标侧键 4");
        text.put("Mouse 5", "鼠标侧键 5");
        text.put("Mouse down", "仅按住鼠标时");
        text.put("Movement Override", "覆盖移动");
        text.put("Multi Attack", "多目标攻击");
        text.put("New", "新版");
        text.put("No Jump Delay", "无跳跃延迟");
        text.put("NoXZ", "无水平击退");
        text.put("No Player Only", "无玩家时显示");
        text.put("None", "无");
        text.put("Normal", "普通");
        text.put("Offhand Items", "副手物品");
        text.put("Old", "旧版");
        text.put("Opal", "Opal 风格");
        text.put("Old Telly", "旧版 Telly");
        text.put("On Release", "松开时触发");
        text.put("Only Best", "仅最佳物品");
        text.put("Only Remote Server", "仅远程服务器");
        text.put("Open Delay", "打开延迟");
        text.put("Ores", "矿石");
        text.put("Outlined 2D", "二维描边");
        text.put("Packet", "数据包");
        text.put("Panel", "面板");
        text.put("Pattern Analysis", "模式分析");
        text.put("Pickaxe Slot", "镐槽位");
        text.put("PickTrash", "拿取杂物");
        text.put("Players", "玩家");
        text.put("PlaySound", "播放声音");
        text.put("Potion", "药水");
        text.put("Predict Ticks", "预测刻数");
        text.put("Prefer Baby", "优先幼年目标");
        text.put("Priority", "优先级");
        text.put("Projectile", "投射物");
        text.put("Punch Bow", "冲击弓");
        text.put("Quartz", "下界石英");
        text.put("Random", "随机");
        text.put("Random Click", "随机点击");
        text.put("Random Pitch Offset", "随机俯仰偏移");
        text.put("Random Yaw Offset", "随机水平偏移");
        text.put("Range", "范围");
        text.put("Ratio", "比例");
        text.put("Recorvey", "自动收回");
        text.put("Redstone", "红石矿");
        text.put("Render Item Spoof", "渲染伪装物品");
        text.put("Reset On Velocity", "受击时重置");
        text.put("Respawn Time", "重生判定时间");
        text.put("RevertOnRegen", "恢复后还原");
        text.put("Right", "右侧");
        text.put("Rotate", "旋转");
        text.put("Rotate Ticks", "旋转刻数");
        text.put("Rotation Tick", "旋转刻");
        text.put("Scale", "缩放");
        text.put("Scan Delay", "扫描延迟");
        text.put("Scoreboard", "计分板");
        text.put("Self Extinguish", "自助灭火");
        text.put("Shield NoSlow", "盾牌无减速");
        text.put("Show Arrows", "显示箭矢");
        text.put("Show Artifacts", "显示异常点");
        text.put("Show Eggs", "显示鸡蛋");
        text.put("Show Health Bar", "显示生命条");
        text.put("Show Pearls", "显示珍珠");
        text.put("Show Potions", "显示药水");
        text.put("Show Snowballs", "显示雪球");
        text.put("Silent", "静默切换");
        text.put("Simple", "简洁");
        text.put("Size", "大小");
        text.put("Skeleton", "骨骼");
        text.put("Slide", "滑动");
        text.put("Slime Ball Slot", "黏液球槽位");
        text.put("Smart Stealing", "智能拿取");
        text.put("Smooth amount", "平滑度");
        text.put("Snap", "视角吸附");
        text.put("Sneak", "潜行");
        text.put("SnowBall", "雪球");
        text.put("Solid check", "实体方块检测");
        text.put("Spawner", "刷怪笼");
        text.put("Speed", "速度");
        text.put("Spiral", "螺旋");
        text.put("Sprint state check", "疾跑状态检测");
        text.put("Strict Host Rock Check", "严格宿主岩石检测");
        text.put("Style", "样式");
        text.put("Switch Back", "切回原工具");
        text.put("Switch Delay", "切换延迟");
        text.put("Switch Delay (Attack Times)", "切换延迟（攻击次数）");
        text.put("Switch Size", "切换数量");
        text.put("Sword Slot", "剑槽位");
        text.put("Tab", "玩家列表");
        text.put("Target ESP", "目标标记");
        text.put("Telly Bridge", "Telly 搭路");
        text.put("Test", "测试");
        text.put("Themis Blink", "Themis 延迟移动");
        text.put("Throw Items", "丢弃物品");
        text.put("Throwables", "投掷物");
        text.put("Top", "顶部");
        text.put("Tracers", "追踪线");
        text.put("Try Attack", "尝试攻击");
        text.put("Use Item Ticks", "使用物品刻数");
        text.put("Valuables", "贵重方块");
        text.put("Vanilla", "原版");
        text.put("Water Bucket Slot", "水桶槽位");
        text.put("Y-Offset", "垂直偏移");

        ZH_CN = Collections.unmodifiableMap(text);
    }

    private UiText() {
    }

    public static String translate(String text) {
        if (text == null || text.isEmpty()) {
            return text;
        }
        return ZH_CN.getOrDefault(text, text);
    }

    public static List<String> translateAll(List<String> values) {
        return values.stream().map(UiText::translate).collect(Collectors.toList());
    }
}
